services:
  # Telegram bot service
  tg_bot:
    container_name: tg_bot
    build:
      target: dev-build
      context: ../
    env_file:
      - .env
    volumes:
      - ../infrastructure/migrations/versions:/app/infrastructure/migrations/versions
    environment:
      TOKEN: ${BOT_TEST_TOKEN}
    restart: unless-stopped

  # PostgreSQL database for bot
  postgres:
    image: postgres:15.3
    container_name: database
    restart: unless-stopped
    volumes:
      - traff_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES__DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES__DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES__DB_NAME}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES__DB_USER} -d ${POSTGRES__DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"

volumes:
  database:
