services:
  # Telegram bot service
  tg_bot:
    container_name: tg_bot
    build:
      target: dev-build
      context: ../backend
      dockerfile: tg_bot/Dockerfile
    env_file:
      - .env
    volumes:
      - ../infrastructure/migrations/versions:/app/infrastructure/migrations/versions
    environment:
      TOKEN: ${BOT_TEST_TOKEN}
      POSTGRES__DB_HOST: ${POSTGRES__DB_HOST}
      POSTGRES__DB_PORT: ${POSTGRES__DB_PORT}
    restart: unless-stopped

  # Telegram API service
  tg_api:
    container_name: tg_api
    build:
      context: ../backend
      dockerfile: tg_api/Dockerfile
      target: dev-build
    volumes:
      - ../backend:/opt/app/
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  # PostgreSQL database for bot
  postgres:
    image: postgres:15.3
    container_name: database
    restart: unless-stopped
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES__DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES__DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES__DB_NAME}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES__DB_USER} -d ${POSTGRES__DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.0.11
    container_name: redis
    ports:
      - "7379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"

volumes:
  database_volume:
