name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
#          ssh -o "StrictHostKeyChecking=no" root@ << 'ENDSSH'
#          cd /home/
#          docker compose -f ./docker/prod.yml down
#          git pull
#          docker compose -f ./docker/prod.yml up -d --build
#          ENDSSH
